/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.twog


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AStandaloneSetup extends AStandaloneSetupGenerated {

	def static void doSetup() {
		new AStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
