grammar com.tmtron.ex.xtext.twog.B with org.eclipse.xtext.xbase.annotations.XbaseWithAnnotations

generate b "http://www.tmtron.com/ex/xtext/twog/B"
import "http://www.tmtron.com/ex/xtext/twog/A" as A

ModelB:
	importSection=XImportSection?
	elements+=AbstractElement+;
	
AbstractElement:
    PackageDeclaration | Use;
	
PackageDeclaration:
    'package' name=QualifiedName '{'
        elements+=AbstractElement*
    '}';		
	
Use:
	'use' name=ValidID def=[A::Definition];
