/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.twog.tests

import com.google.inject.Inject
import com.tmtron.ex.xtext.twog.b.ModelB
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CustomInjectorProvider)
class BParsingTest {
	@Inject
	ParseHelper<ModelB> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			use Use1 Adef1
			use Use2 Adef2
		''')
		Assert.assertNotNull(result)
	}
}
